#!/usr/bin/python2.7
import cgi
import cgitb
cgitb.enable()

from pymongo import MongoClient

form = cgi.FieldStorage()

MongoClient().musicstudy.nationality.insert_one({'user': form['username'].value, 'nationality': form['nationality'].value})

print("Refresh: 0; /survey.html")
print("")
