#!/usr/bin/python2.7
import cgi
import cgitb
cgitb.enable()

print("Content-Type: text/html")
print("")

from pymongo import MongoClient
from collections import Counter
import csv

db = MongoClient().musicstudy

total_trials = {}
aggregate = {}

aggregate_csv = []
details_csv = []
participants_csv = []

indexes = {'r': 0, 'gf': 1, 'gs': 2}
def cindex(s):
	return indexes[s[:-1]]
completed_trial = Counter()
for i in range(10):
	for n in indexes:
		completed_trial[n + str(i)] += 1

for entry in db.prefer.find():
	u = entry['user']
	if u not in aggregate:
		aggregate[u] = [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
		total_trials[u] = Counter()
	aggregate[u][int(entry['cond'])][cindex(entry['prefer'])] += 1
	total_trials[u][entry['prefer']] += 1
	total_trials[u][entry['over']] += 1

complete = set()

for key, value in total_trials.iteritems():
	if value == completed_trial:
		complete.add(key)

for entry in db.prefer.find():
	if entry['user'] in complete:
		details_csv.append([entry['user'], entry['prefer'], entry['over']])
details_csv.sort()

for u, p in aggregate.iteritems():
	if u in complete:
		for cond, counts in enumerate(p):
			aggregate_csv.append([u, cond] + counts)

print'<p>', len(complete), "surveys completed"
print'<p>', len(aggregate), "surveys started"
print'<p><a href="../o/aggregate.csv">aggregate</a>'
print'<p><a href="../o/details.csv">details</a>'
print'<p><a href="../o/participants.csv">participants</a>'

for entry in db.nationality.find():
	if True:#entry['user'] in complete:
		participants_csv.append([entry['user'], entry['age'], entry['nationality'], entry['musicaltraining'], entry['gender']])

with open('../o/aggregate.csv', 'wb') as f:
	csv.writer(f).writerows(aggregate_csv)

with open('../o/details.csv', 'wb') as f:
	csv.writer(f).writerows(details_csv)

with open('../o/participants.csv', 'wb') as f:
	csv.writer(f).writerows(participants_csv)

